export default {
  watch: {
    type: "pot",
    name: "watch",
    unlocked: true,
    count: 0,
    messages: [
      "you watch the pot...\n",
      "you watch the pot some more...\n",
      "you continue watching the pot...\n",
    ],
  },
  blow: {
    type: "pot",
    name: "blow",
    unlocked: false,
    count: 0,
    requirement: { type: "actions", name: "watch", count: 3 },
  },
  rub: {
    type: "fire",
    name: "rub",
    unlocked: false,
    count: 0,
    requirement: { type: "inventory", name: "sticks", count: 2 },
  },
  kindle: {
    type: "fire",
    name: "kindle",
    unlocked: false,
    count: 0,
    requirement: { type: "inventory", name: "kindling", count: 5 },
  },
  place: {
    type: "fire",
    name: "place",
    unlocked: false,
    count: 0,
    requirement: { type: "fire", name: "state", notValue: "cold" },
  },
  stack: {
    type: "fire",
    name: "stack",
    unlocked: false,
    count: 0,
    requirement: { type: "inventory", name: "logs", count: 1 },
  },
  look: {
    type: "environment",
    name: "look",
    unlocked: false,
    used: 0,
  },
  gather: {
    type: "environment",
    name: "gather",
    unlocked: false,
    used: 0,
    requirement: { type: "actions", name: "blow", count: 1 },
  },
  chop: {
    type: "environment",
    name: "chop",
  },
};
